server:
  port: 8079
  servlet:
    context-path: /Destinos
    
  error:
    include-details: always

# Configuraciones de la web          
  mvc:
    view:
      prefix: resources/templates
      suffix: html
               
# Conexión a MySQL

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/destinos
    username: root
    password: archipielagoM1
    driver-class-name: com.mysql.cj.jdbc.Driver

# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka

    