spring:
  application:
    name: Itinerario
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
         max-attempts: 20
         max-internal: 15000
         initial-interval: 10000


