server:
  port: 8888
 
spring:
  application:
    name: ms-admin-config-server
    
  profiles:
    active: native
    
  #cloud:
  #  config:
  #    server:
  #      native:
  #        search-locations: ///C:\Users\Brayham\Documents\workspace-spring-tool-suite-4-4.18.0.RELEASE\ms-gestion-config-data\ms-gestion-config-data
          
          
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Isntlambo/DestinosV2.git
          search-paths: /ms-gestion-config-data/ms-gestion-config-data
          username: 
          password: 
          default-label: main
          cloneOnStart: true